apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: hello-world-rollout
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: mwqar/express-hello:latest
        ports:
        - containerPort: 4502
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 50
      - pause: {duration: 30s}

